import "https://deno.land/x/xhr@0.1.0/mod.ts";
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { topic } = await req.json();
    
    if (!topic) {
      throw new Error('Topic is required');
    }

    console.log('Exploring topic:', topic);

    // Get API keys
    const geminiApiKey = Deno.env.get('GEMINI_API_KEY');
    const geminiApiKeySecondary = Deno.env.get('GEMINI_API_KEY_SECONDARY');
    const youtubeApiKey = Deno.env.get('YOUTUBE_API_KEY');
    const redditApiKey = Deno.env.get('REDDIT_API_KEY');
    const tavilyApiKey = Deno.env.get('TAVILY_API_KEY');

    if (!geminiApiKey && !geminiApiKeySecondary) {
      throw new Error('GEMINI_API_KEY or GEMINI_API_KEY_SECONDARY must be configured');
    }

    // Helper function to call Gemini API with fallback
    const callGeminiAPI = async (prompt: string, apiKey: string) => {
      const response = await fetch(
        `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`,
        {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            contents: [{
              parts: [{
                text: prompt
              }]
            }],
            generationConfig: {
              temperature: 0.3,
              topK: 20,
              topP: 0.8,
              maxOutputTokens: 800, // Reduced to avoid token limits
              responseMimeType: "application/json"
            }
          })
        }
      );

      if (!response.ok) {
        throw new Error(`Gemini API error: ${response.status}`);
      }

      return response.json();
    };

    // Topic-specific prompt for generating relevant learning tasks
    const geminiPrompt = `Generate learning content for "${topic}". Create specific, actionable tasks related to ${topic}.

{
  "overview": "Brief overview of ${topic} (max 150 words)",
  "tips": [
    "Tip 1 specific to ${topic}",
    "Tip 2 specific to ${topic}",
    "Tip 3 specific to ${topic}",
    "Tip 4 specific to ${topic}",
    "Tip 5 specific to ${topic}"
  ],
  "learningSteps": [
    {
      "id": "step-1",
      "title": "Task title specific to ${topic}",
      "description": "Specific action for ${topic}",
      "completed": false
    }
  ]
}

Create 8 progressive learning steps that are specific to ${topic}. Each step should be a concrete task someone can do to learn ${topic}. Return only valid JSON.`;

    console.log('Calling Gemini API...');
    let geminiData;
    const currentApiKey = geminiApiKey || geminiApiKeySecondary;
    
    if (!currentApiKey) {
      throw new Error('No Gemini API keys available');
    }
    
    try {
      geminiData = await callGeminiAPI(geminiPrompt, currentApiKey);
    } catch (error) {
      console.error('Primary Gemini API error:', error);
      // Try secondary key if primary fails
      if (geminiApiKeySecondary && currentApiKey === geminiApiKey) {
        console.log('Trying secondary Gemini API key...');
        try {
          geminiData = await callGeminiAPI(geminiPrompt, geminiApiKeySecondary);
        } catch (secondaryError) {
          console.error('Secondary Gemini API error:', secondaryError);
          const errorMessage = error instanceof Error ? error.message : 'Unknown error';
          throw new Error(`Both Gemini API keys failed: ${errorMessage}`);
        }
      } else {
        throw error;
      }
    }
    const geminiContent = geminiData.candidates?.[0]?.content?.parts?.[0]?.text;
    
    console.log('Full Gemini API response:', JSON.stringify(geminiData, null, 2));
    
    if (!geminiContent) {
      console.error('No content in Gemini response. Structure:', {
        candidates: geminiData.candidates,
        candidateCount: geminiData.candidates?.length,
        firstCandidate: geminiData.candidates?.[0],
        content: geminiData.candidates?.[0]?.content,
        parts: geminiData.candidates?.[0]?.content?.parts,
        finishReason: geminiData.candidates?.[0]?.finishReason
      });
      
      // If we hit token limits, use fallback
      if (geminiData.candidates?.[0]?.finishReason === 'MAX_TOKENS') {
        console.log('Hit token limits, using fallback content');
      } else {
        throw new Error('No content generated by Gemini');
      }
    }

    console.log('Raw Gemini response:', geminiContent);

    // Parse Gemini response with better error handling
    let geminiJsonStr = geminiContent?.trim() || '';
    if (geminiJsonStr.startsWith('```json')) {
      geminiJsonStr = geminiJsonStr.slice(7);
    }
    if (geminiJsonStr.startsWith('```')) {
      geminiJsonStr = geminiJsonStr.slice(3);
    }
    if (geminiJsonStr.endsWith('```')) {
      geminiJsonStr = geminiJsonStr.slice(0, -3);
    }
    geminiJsonStr = geminiJsonStr.trim();

    let geminiResult;
    try {
      // If content is empty or truncated, use fallback
      if (!geminiJsonStr || geminiData.candidates?.[0]?.finishReason === 'MAX_TOKENS') {
        throw new Error('Content truncated due to token limits');
      }
      geminiResult = JSON.parse(geminiJsonStr);
    } catch (parseError) {
      console.error('Gemini JSON parse error:', parseError);
      console.error('Content to parse:', geminiJsonStr);
      console.error('Finish reason:', geminiData.candidates?.[0]?.finishReason);
      
      // Enhanced fallback content with topic-specific tasks
      const topicLower = topic.toLowerCase();
      const generateTopicSpecificSteps = (topic: string) => {
        const commonPatterns = {
          programming: [
            { title: "Set up development environment", description: `Install necessary tools and IDE for ${topic}` },
            { title: "Write your first program", description: `Create a simple "Hello World" program in ${topic}` },
            { title: "Learn basic syntax", description: `Study variables, functions, and control structures in ${topic}` },
            { title: "Practice with exercises", description: `Complete coding challenges and exercises in ${topic}` },
            { title: "Build a small project", description: `Create a practical application using ${topic}` },
            { title: "Debug and test code", description: `Learn debugging techniques and testing in ${topic}` },
            { title: "Explore frameworks", description: `Investigate popular frameworks and libraries for ${topic}` },
            { title: "Join the community", description: `Participate in ${topic} forums and contribute to projects` }
          ],
          design: [
            { title: "Learn design principles", description: `Study color theory, typography, and layout in ${topic}` },
            { title: "Practice with tools", description: `Get familiar with design software for ${topic}` },
            { title: "Study examples", description: `Analyze successful ${topic} examples and case studies` },
            { title: "Create mockups", description: `Design wireframes and prototypes for ${topic}` },
            { title: "Get feedback", description: `Share your ${topic} work and gather constructive criticism` },
            { title: "Iterate and improve", description: `Refine your ${topic} skills based on feedback` },
            { title: "Build a portfolio", description: `Showcase your best ${topic} projects` },
            { title: "Stay updated", description: `Follow ${topic} trends and emerging techniques` }
          ],
          language: [
            { title: "Learn basic vocabulary", description: `Master essential words and phrases in ${topic}` },
            { title: "Practice pronunciation", description: `Work on speaking and accent in ${topic}` },
            { title: "Study grammar rules", description: `Understand sentence structure and grammar in ${topic}` },
            { title: "Listen actively", description: `Consume ${topic} media like podcasts and videos` },
            { title: "Practice conversation", description: `Find speaking partners for ${topic} practice` },
            { title: "Read regularly", description: `Read books, articles, and news in ${topic}` },
            { title: "Write daily", description: `Keep a journal or blog in ${topic}` },
            { title: "Take a proficiency test", description: `Assess your ${topic} level with official tests` }
          ],
          science: [
            { title: "Understand fundamentals", description: `Learn basic concepts and terminology in ${topic}` },
            { title: "Study key theories", description: `Explore major theories and principles of ${topic}` },
            { title: "Conduct experiments", description: `Perform hands-on experiments related to ${topic}` },
            { title: "Analyze data", description: `Learn to collect and interpret ${topic} data` },
            { title: "Read research papers", description: `Study current research and findings in ${topic}` },
            { title: "Use scientific tools", description: `Get familiar with equipment and software for ${topic}` },
            { title: "Present findings", description: `Practice communicating ${topic} concepts clearly` },
            { title: "Apply knowledge", description: `Use ${topic} principles to solve real-world problems` }
          ]
        };

        // Determine topic category and return appropriate steps
        if (topicLower.includes('programming') || topicLower.includes('coding') || topicLower.includes('javascript') || topicLower.includes('python') || topicLower.includes('java') || topicLower.includes('react') || topicLower.includes('web development')) {
          return commonPatterns.programming;
        } else if (topicLower.includes('design') || topicLower.includes('ui') || topicLower.includes('ux') || topicLower.includes('graphic') || topicLower.includes('photography') || topicLower.includes('art')) {
          return commonPatterns.design;
        } else if (topicLower.includes('language') || topicLower.includes('english') || topicLower.includes('spanish') || topicLower.includes('french') || topicLower.includes('german') || topicLower.includes('chinese') || topicLower.includes('japanese')) {
          return commonPatterns.language;
        } else if (topicLower.includes('science') || topicLower.includes('physics') || topicLower.includes('chemistry') || topicLower.includes('biology') || topicLower.includes('mathematics') || topicLower.includes('math')) {
          return commonPatterns.science;
        } else {
          // Generic but topic-specific fallback
          return [
            { title: `${topic} Fundamentals`, description: `Master the basic concepts and principles of ${topic}` },
            { title: `${topic} Terminology`, description: `Learn key terms and vocabulary specific to ${topic}` },
            { title: `${topic} Practice`, description: `Apply ${topic} concepts through hands-on exercises` },
            { title: `${topic} Tools`, description: `Get familiar with essential tools and resources for ${topic}` },
            { title: `${topic} Community`, description: `Connect with other ${topic} learners and experts` },
            { title: `${topic} Projects`, description: `Work on practical projects to deepen ${topic} understanding` },
            { title: `${topic} Advanced Topics`, description: `Explore more complex aspects of ${topic}` },
            { title: `${topic} Mastery`, description: `Achieve proficiency and teach others about ${topic}` }
          ];
        }
      };

      const topicSteps = generateTopicSpecificSteps(topic);
      
      geminiResult = {
        overview: `${topic} is a valuable subject that offers diverse learning opportunities and practical applications. Understanding ${topic} requires a structured approach, starting with fundamentals and progressively building expertise through practice and real-world application.`,
        tips: [
          `Start with the core fundamentals of ${topic} to build a solid foundation`,
          `Practice ${topic} regularly through hands-on exercises and projects`,
          `Join ${topic} communities to learn from experienced practitioners`,
          `Use multiple learning resources to gain comprehensive ${topic} knowledge`,
          `Set specific, measurable goals for your ${topic} learning journey`
        ],
        learningSteps: topicSteps.map((step, index) => ({
          id: `step-${index + 1}`,
          title: step.title,
          description: step.description,
          completed: false
        }))
      };
    }

    // Fetch YouTube videos
    let videos = [];
    if (youtubeApiKey) {
      try {
        console.log('Searching YouTube videos...');
        const youtubeResponse = await fetch(
          `https://www.googleapis.com/youtube/v3/search?part=snippet&q=${encodeURIComponent(topic + ' tutorial')}&type=video&maxResults=5&key=${youtubeApiKey}`
        );

        if (youtubeResponse.ok) {
          const youtubeData = await youtubeResponse.json();
          videos = youtubeData.items?.map((item: any) => ({
            title: item.snippet.title,
            url: `https://www.youtube.com/watch?v=${item.id.videoId}`,
            description: item.snippet.description.substring(0, 150) + '...'
          })) || [];
          console.log(`Found ${videos.length} YouTube videos`);
        }
      } catch (error) {
        console.error('YouTube API error:', error);
      }
    }

    // Fallback videos if YouTube API fails
    if (videos.length === 0) {
      videos = [
        {
          title: `Learn ${topic} - Beginner's Guide`,
          url: `https://www.youtube.com/results?search_query=${encodeURIComponent(topic + ' tutorial')}`,
          description: `Comprehensive tutorial covering the basics of ${topic}`
        },
        {
          title: `${topic} Fundamentals`,
          url: `https://www.youtube.com/results?search_query=${encodeURIComponent(topic + ' fundamentals')}`,
          description: `Understanding the core concepts of ${topic}`
        },
        {
          title: `Advanced ${topic} Techniques`,
          url: `https://www.youtube.com/results?search_query=${encodeURIComponent(topic + ' advanced')}`,
          description: `Deep dive into advanced ${topic} concepts and techniques`
        }
      ];
    }

    // Fetch Reddit communities
    let communities = [];
    try {
      console.log('Searching Reddit communities...');
      const redditResponse = await fetch(
        `https://www.reddit.com/subreddits/search.json?q=${encodeURIComponent(topic)}&limit=5`,
        {
          headers: {
            'User-Agent': 'LearningApp/1.0'
          }
        }
      );

      if (redditResponse.ok) {
        const redditData = await redditResponse.json();
        communities = redditData.data?.children?.map((item: any) => ({
          name: item.data.display_name_prefixed,
          url: `https://www.reddit.com${item.data.url}`,
          platform: "Reddit",
          description: item.data.public_description || `Community for ${topic} enthusiasts`
        })) || [];
        console.log(`Found ${communities.length} Reddit communities`);
      }
    } catch (error) {
      console.error('Reddit API error:', error);
    }

    // Add fallback communities
    if (communities.length === 0) {
      communities = [
        {
          name: `r/${topic.toLowerCase().replace(/\s+/g, '')}`,
          url: `https://www.reddit.com/search/?q=${encodeURIComponent(topic)}`,
          platform: "Reddit",
          description: `Community for ${topic} enthusiasts and learners`
        }
      ];
    }

    // Add other community suggestions
    communities.push(
      {
        name: `${topic} Discord Server`,
        url: `https://discord.com/invite/search?q=${encodeURIComponent(topic)}`,
        platform: "Discord",
        description: `Real-time chat community for ${topic} learners`
      },
      {
        name: `${topic} Stack Overflow`,
        url: `https://stackoverflow.com/questions/tagged/${encodeURIComponent(topic.toLowerCase().replace(/\s+/g, '-'))}`,
        platform: "Stack Overflow",
        description: `Q&A community for technical ${topic} questions`
      }
    );

    // Fetch Wikipedia articles using official Wikipedia API with improved relevance
    interface WikipediaArticle {
      title: string;
      url: string;
      description: string;
      thumbnail: string | null;
    }
    
    let wikipediaArticles: WikipediaArticle[] = [];
    try {
      console.log('Searching Wikipedia articles...');
      
      // Create more specific search terms for better relevance
      const searchTerms = [
        topic,
        `${topic} techniques`,
        `${topic} fundamentals`,
        `${topic} tutorial`
      ];
      
      const allResults: any[] = [];
      
      // Search with multiple specific terms
      for (const searchTerm of searchTerms) {
        try {
          const searchResponse = await fetch(
            `https://en.wikipedia.org/w/api.php?action=query&list=search&srsearch=${encodeURIComponent(searchTerm)}&format=json&srlimit=3&origin=*`
          );

          if (searchResponse.ok) {
            const searchData = await searchResponse.json();
            const searchResults = searchData.query?.search || [];
            
            // Filter out irrelevant results (movies, TV shows, specific products unless the topic is about them)
            const filteredResults = searchResults.filter((result: any) => {
              const title = result.title.toLowerCase();
              const snippet = result.snippet.toLowerCase();
              const topicLower = topic.toLowerCase();
              
              // Exclude specific movies, TV shows, games unless the topic is specifically about entertainment
              const isEntertainmentSpecific = title.includes('(film)') || 
                                            title.includes('(movie)') || 
                                            title.includes('(tv series)') || 
                                            title.includes('(video game)') ||
                                            title.includes('(album)') ||
                                            title.includes('(song)');
              
              const isTopicAboutEntertainment = topicLower.includes('film') || 
                                              topicLower.includes('movie') || 
                                              topicLower.includes('cinema') ||
                                              topicLower.includes('entertainment');
              
              // If it's entertainment-specific content, only include if the topic is about entertainment
              if (isEntertainmentSpecific && !isTopicAboutEntertainment) {
                return false;
              }
              
              // Prefer educational, technical, or general concept articles
              const isEducational = snippet.includes('technique') || 
                                   snippet.includes('method') || 
                                   snippet.includes('process') ||
                                   snippet.includes('study') ||
                                   snippet.includes('field') ||
                                   snippet.includes('discipline') ||
                                   title.toLowerCase().includes(topicLower);
              
              return isEducational || !isEntertainmentSpecific;
            });
            
            allResults.push(...filteredResults);
          }
        } catch (searchError) {
          console.error(`Error searching for term "${searchTerm}":`, searchError);
        }
      }
      
      // Remove duplicates and prioritize by relevance
      const uniqueResults = allResults.filter((result, index, self) => 
        index === self.findIndex(r => r.title === result.title)
      );
      
      // Sort by relevance (title similarity to topic gets priority)
      const sortedResults = uniqueResults.sort((a, b) => {
        const aRelevance = a.title.toLowerCase().includes(topic.toLowerCase()) ? 1 : 0;
        const bRelevance = b.title.toLowerCase().includes(topic.toLowerCase()) ? 1 : 0;
        return bRelevance - aRelevance;
      });
      
      console.log(`Found ${sortedResults.length} filtered search results`);
      
      // Get summaries for top results
      for (const result of sortedResults.slice(0, 4)) {
        try {
          const summaryResponse = await fetch(
            `https://en.wikipedia.org/w/api.php?action=query&prop=extracts&exintro&titles=${encodeURIComponent(result.title)}&format=json&origin=*`
          );
          
          if (summaryResponse.ok) {
            const summaryData = await summaryResponse.json();
            const pages = summaryData.query?.pages || {};
            const pageId = Object.keys(pages)[0];
            const page = pages[pageId];
            
            if (page && page.extract) {
              // Clean up the extract (remove HTML tags and limit length)
              let cleanExtract = page.extract.replace(/<[^>]*>/g, '');
              if (cleanExtract.length > 200) {
                cleanExtract = cleanExtract.substring(0, 200) + '...';
              }
              
              wikipediaArticles.push({
                title: result.title,
                url: `https://en.wikipedia.org/wiki/${encodeURIComponent(result.title.replace(/ /g, '_'))}`,
                description: cleanExtract || result.snippet || `Wikipedia article about ${result.title}`,
                thumbnail: null
              });
            }
          }
        } catch (summaryError) {
          console.error(`Error fetching summary for ${result.title}:`, summaryError);
          // Add without summary if summary fetch fails
          wikipediaArticles.push({
            title: result.title,
            url: `https://en.wikipedia.org/wiki/${encodeURIComponent(result.title.replace(/ /g, '_'))}`,
            description: result.snippet || `Wikipedia article about ${result.title}`,
            thumbnail: null
          });
        }
      }
      
      console.log(`Successfully fetched ${wikipediaArticles.length} relevant Wikipedia articles`);
    } catch (error) {
      console.error('Wikipedia API error:', error);
    }

    // Improved fallback articles if API fails
    if (wikipediaArticles.length === 0) {
      console.log('Using improved fallback Wikipedia articles');
      wikipediaArticles = [
        {
          title: topic,
          url: `https://en.wikipedia.org/wiki/${encodeURIComponent(topic.replace(/ /g, '_'))}`,
          description: `Comprehensive Wikipedia article about ${topic}`,
          thumbnail: null
        },
        {
          title: `${topic.split(' ')[0]}`, // First word of topic
          url: `https://en.wikipedia.org/wiki/${encodeURIComponent(topic.split(' ')[0])}`,
          description: `Learn about ${topic.split(' ')[0]} fundamentals`,
          thumbnail: null
        },
        {
          title: "Learning",
          url: "https://en.wikipedia.org/wiki/Learning",
          description: "Process of acquiring new understanding, knowledge, behaviors, and skills",
          thumbnail: null
        }
      ];
    }

    // Generate image suggestions using Tavily or fallback
    let images = [];
    if (tavilyApiKey) {
      try {
        console.log('Searching for educational images...');
        const tavilyResponse = await fetch('https://api.tavily.com/search', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${tavilyApiKey}`
          },
          body: JSON.stringify({
            query: `${topic} educational diagrams infographics`,
            search_depth: 'basic',
            include_images: true,
            max_results: 4
          })
        });

        if (tavilyResponse.ok) {
          const tavilyData = await tavilyResponse.json();
          images = tavilyData.images?.slice(0, 3).map((img: any) => ({
            title: `${topic} Visual Guide`,
            url: img.url,
            description: `Educational visual resource for understanding ${topic}`
          })) || [];
          console.log(`Found ${images.length} educational images`);
        }
      } catch (error) {
        console.error('Tavily API error:', error);
      }
    }

    // Fallback images
    if (images.length === 0) {
      images = [
        {
          title: `${topic} Infographic`,
          url: `https://www.google.com/search?q=${encodeURIComponent(topic + ' infographic')}&tbm=isch`,
          description: `Visual representations and infographics about ${topic}`
        },
        {
          title: `${topic} Diagrams`,
          url: `https://www.google.com/search?q=${encodeURIComponent(topic + ' diagram')}&tbm=isch`,
          description: `Diagrams and charts explaining ${topic} concepts`
        },
        {
          title: `${topic} Visual Guide`,
          url: `https://www.google.com/search?q=${encodeURIComponent(topic + ' visual guide')}&tbm=isch`,
          description: `Visual learning materials for ${topic}`
        }
      ];
    }

    const result = {
      overview: geminiResult.overview,
      videos: videos.slice(0, 4),
      tips: geminiResult.tips,
      learningSteps: geminiResult.learningSteps || [],
      images: images.slice(0, 3),
      communities: communities.slice(0, 5),
      wikipediaArticles: wikipediaArticles.slice(0, 3)
    };

    console.log('Successfully processed topic exploration with real API data');

    return new Response(JSON.stringify(result), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });

  } catch (error) {
    console.error('Error in explore-topic function:', error);
    const errorMessage = error instanceof Error ? error.message : 'Unknown error occurred';
    return new Response(JSON.stringify({ error: errorMessage }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});